netifd: place common network scripts under /lib/ to fix conflict issues with mlib packages
When we try to install <mlib>-netifd (lib32-netifd) and netifd packages,
the /etc/init.d/network and /sbin/ifup.netifd conflict due to placing
of network scripts under different directories.

Error log:
-- snip --
  Error: Transaction check error:
  file /etc/init.d/network conflicts between attempted installs of netifd-git-r0.corei7_64 and lib32-netifd-git-r0.i586
  file /sbin/ifup.netifd conflicts between attempted installs of netifd-git-r0.corei7_64 and lib32-netifd-git-r0.i586
-- snip --

Hence place the scripts (which are common) under /lib/ directory.

Also, remove "rm -rf ${D}/lib/", as it leads to not shipping
network scripts when BASELIB is lib.

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>