ipset: replace PN with BPN in SRC_URI to fix fetch error with mlib-ipset
The <mlib>-ipset (example: lib32-ipset) fetch fails with below error:
-- snip --
ERROR: could not open HSTS store at '/local/ferret/.wget-hsts'. HSTS will be disabled.
--2018-03-06 16:10:32--  http://ipset.netfilter.org/lib32-ipset-6.24.tar.bz2
Resolving ipset.netfilter.org... 150.214.142.167
Connecting to ipset.netfilter.org|150.214.142.167|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2018-03-06 16:10:33 ERROR 404: Not Found.

ERROR: lib32-ipset-6.24-r0 do_fetch: Fetcher failure for URL: 'http://ipset.netfilter.org/lib32-ipset-6.24.tar.bz2'. Unable to fetch URL from any source.
ERROR: lib32-ipset-6.24-r0 do_fetch: Function failed: base_do_fetch
-- snip --

Hence replace PN with BPN.

Signed-off-by: Jagadeesh Krishnanjanappa <jkrishnanjanappa@mvista.com>